### ISSUE TITLE
It is unclear why http://vuejs-news.herokuapp.com/ is working properly

### ISSUE THREAD

**Issue by fbigun** [olayinkaos/vuejs-news#2]
http://vuejs-news.herokuapp.com/

Why the example config.js API can see the New York Times without setting.
I copied config.js.example directly config.js not normal.Error accessing https://api.nytimes.com/svc/topstories/v2/books.json?api-key=YOUR_NYT_API_KEY

I am confused now.

**Comment by olayinkaos** [comment]
Hey @fbigun!
On the Heroku demo, I moved the key to a Node.js backend so as to avoid abuse. So, it calls my API (which wraps the NYT API) instead of the NYT API directly.

You should replace the value of `YOUR_NYT_API_KEY` with your actual key gotten from the NYT Developer website and retry your app. Let me know how this goes.
